layout_spectrum: 0.2813283
typography_spectrum: 0.7670873
color:
  saturation: 0.71487
  lightness: 0.4167771
  brandStrength: 0.01712499
  brandColors:
    - '#7B99D7'
    - '#2A478B'
    - '#B2D0E7'
    - '#0F1316'
    - '#40D0F6'
  rhythmicContrast: 0.7490324
name: Testina
